WIP: Feat/arch pkgbuild
animo/aries-cli pull request #157
Opened 2022-04-07 20:39 UTC by morrieinmaas

First simple PKGBUILD added

See commit for TODOS

2022-04-07 20:41 UTC, morrieinmaas commented on docs/features/environments.md
>      token: ~
This change will be removed - sorry that was my linter/auto-formatting @blu3beri

2022-04-07 20:41 UTC, blu3beri commented
Any reason why `/usr/local/share`? And what if the dir does not exist?

2022-04-07 20:43 UTC, blu3beri commented
I am not too sure but so we have write access to /usr/local/bin?

2022-04-07 20:43 UTC, morrieinmaas commented
Just first draft @blu3beri. will need to test this and spin up an arch machine for this

2022-04-07 20:45 UTC, morrieinmaas commented
Yeah I'm also not sure. Otherwise /usr/bin is where binaries live if I remember correctly. I'll give that a try tomorrow. Open to and happy for suggestions if you know the way to go here

2022-04-07 20:50 UTC, blu3beri commented
> Yeah I'm also not sure. Otherwise /usr/bin is where binaries live if I remember correctly. I'll give that a try tomorrow. Open to and happy for suggestions if you know the way to go here

`/usr/bin` is protected for sure. However yay 99% requires sudo so we might just have to curl it to `tmp` and sudo mv it. Just guessing here. I think I would prefer `/usr/local/bin` but we should just follow aur conventions ;).

2022-04-08 07:40 UTC, morrieinmaas commented
sounds good to me. I'll give it a go

2022-04-08 15:09 UTC, blu3beri requested changes

2022-04-08 15:09 UTC, blu3beri commented on PKGBUILD
> +  echo "Successfully installed aries-cli"
Id remove the echo and keep it just to the install. If it works I will accept it.

2022-04-08 15:10 UTC, blu3beri commented on docs/features/environments.md
> +{% hint style="warning" %}
Remove this commit from your pr :d

2022-04-08 15:10 UTC, morrieinmaas commented on docs/features/environments.md
> +{% hint style="warning" %}
ok nice - will remove it. tested it today and install worked with yay

2022-04-08 15:11 UTC, morrieinmaas commented on docs/features/environments.md
> +{% hint style="warning" %}
i'll make a pipeline for auto release AUR on release of new version in a separate PR then. started on it already

2022-04-08 15:12 UTC, morrieinmaas commented on docs/features/environments.md
> +{% hint style="warning" %}
@blu3beri aaaand changes puuuuuuuushT

2022-04-08 15:16 UTC, morrieinmaas commented on PKGBUILD
> +  echo "Successfully installed aries-cli"
done

2022-04-08 15:16 UTC, morrieinmaas commented on docs/features/environments.md
> +{% hint style="warning" %}
ah damn sorry this one - will do- lol

2022-04-08 15:19 UTC, morrieinmaas commented
@blu3beri alright should be good to go now

2022-04-08 17:59 UTC, blu3beri requested changes
Great work!

Just one small thing, can we create a folder `pkg` with a folder `aur` and put it in there? Then we can just manage it from there for all the other repos :)

2022-04-08 18:40 UTC, morrieinmaas commented
thanks. and of course. let me push that

2022-04-08 18:55 UTC, blu3beri commented
> thanks. and of course. let me push that

2022-04-08 18:57 UTC, morrieinmaas commented
@blu3beri done

2022-04-09 09:56 UTC, blu3beri approved these changes

2022-04-09 09:57 UTC, merged